### ISSUE TITLE
Vallox mqtt

### ISSUE THREAD

**Issue by cheick66** [mruettgers/vallox-mqtt-bridge#1]
Hallo Michael,
ich habe versucht Dein Docker Image zu starten, jedoch scheint mir da etwas zu fehlen.

"docker pull" war okay und die "config.yml" habe ich mit den IP-Adressen angepasst.
Beim Start scheint jedoch noch ein Config File zu fehlen. Wo kann ich das finden?
```
docker run -v Vallox_config.yml:/opt/valox-mqtt-bridge/config.yml mruettgers/vallox-mqtt-bridge
Config file /config/vallox-mqtt-bridge.yml does not exist
```

Hättest Du eventuell auch ein Beispiel für docker-compose, was ich bisher verwendet habe?

VG   Christian

**Comment by mruettgers** [comment]
Hey Christian,

sorry, war wohl im README falsch.
Standardmäßig erwartet das Docker-Image die Config hier: `/config/vallox-mqtt-bridge.yml`.
Das lässt sich sonst über die Umgebungsvariable `CONFIG`  steuern.

So sollte es gehen:

```
docker run -v Vallox_config.yml:/config/vallox-mqtt-bridge.yml mruettgers/vallox-mqtt-bridge
```

Docker Compose Beispiel:
```
version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    networks:
      services:
        ipv4_address: 10.4.32.103
      backend:
    volumes:
      - ./mosquitto/config/:/etc/mosquitto/
    logging:
      options:
        tag: mosquitto

  vallox2mqtt:
    image: mruettgers/vallox-mqtt-bridge
    restart: unless-stopped
    networks:
      backend:
      frontend:
    depends_on:
      - mosquitto
    links:
      - mosquitto
    volumes:
     - ./vallox2mqtt/config/:/config/:ro
    logging:
      options:
        tag: vallox2mqtt

networks:
  frontend:
  backend:
    internal: true
  services:
    external:
      name: services
```

Services ist ein macvlan-Netzwerk zu meinem lokalen Netz, habe also nicht mit Port-Forwardings beim Mosquitto gearbeitet.


Viele Grüße,

Michael

**Comment by mruettgers** [comment]
@cheick66 Hallo Christian, 

es gab noch einen Typo im Konfigurationsbeispiel. Ich habe das gerade mal korrigiert. `vallox`  statt ` valox` muss es heißen. Sorry.

Hier mal meine Config, die mit dem frischen Docker-Image, das ich gerade eben gepusht habe (arm/v7, arm64 und amd64), funktioniert.

```
fetch_interval: 300

vallox:
  unit:
    host: 10.4.35.232
    port: 80
  
mqtt:
  broker:
    host: mosquitto
  base_topic: ventilation/unit/1

metrics:
  - A_CYC_FAN_SPEED
  - A_CYC_TEMP_EXTRACT_AIR
  - A_CYC_TEMP_EXHAUST_AIR
  - A_CYC_TEMP_OUTDOOR_AIR
  - A_CYC_TEMP_SUPPLY_CELL_AIR
  - A_CYC_TEMP_SUPPLY_AIR
  - A_CYC_RH_LEVEL
  - A_CYC_CO2_LEVEL
  - A_CYC_EXTR_FAN_SPEED
  - A_CYC_SUPP_FAN_SPEED
  - A_CYC_RH_VALUE
```


Vg,

Michael

**Comment by cheick66** [comment]
Hallo Michael,Da hatte ich ja Glück, dass ich keine Zeit hatte. Ich schau es mir aber noch an.Vielen Dank     Christian Am 04.12.2022 11:09 schrieb Michael Rüttgers ***@***.***>:

@cheick66 Hallo Christian,

es gab noch einen Typo im Konfigurationsbeispiel. Ich habe das gerade mal korrigiert. vallox  statt  valox muss es heißen. Sorry.

Hier mal meine Config, die mit dem frischen Docker-Image, das ich gerade eben gepusht habe (arm/v7, arm64 und amd64), funktioniert.

fetch_interval: 300



vallox:

  unit:

    host: 10.4.35.232

    port: 80

  

mqtt:

  broker:

    host: mosquitto

  base_topic: ventilation/unit/1



metrics:

  - A_CYC_FAN_SPEED

  - A_CYC_TEMP_EXTRACT_AIR

  - A_CYC_TEMP_EXHAUST_AIR

  - A_CYC_TEMP_OUTDOOR_AIR

  - A_CYC_TEMP_SUPPLY_CELL_AIR

  - A_CYC_TEMP_SUPPLY_AIR

  - A_CYC_RH_LEVEL

  - A_CYC_CO2_LEVEL

  - A_CYC_EXTR_FAN_SPEED

  - A_CYC_SUPP_FAN_SPEED

  - A_CYC_RH_VALUE



Vg,

Michael

**Comment by cheick66** [comment]
Hallo Michael,
nach langer Pause habe ich es nun wieder in Angriff genommen und es funktioniert.

Mein .yml File:
  vallox:
    image: mruettgers/vallox-mqtt-bridge:latest
    restart: always
    volumes:
      - ./vallox/Vallox_config.yml:/config/vallox-mqtt-bridge.yml

Nun läuft es und ich bekomme in meinem SmartHome auch die Werte.
Durch das autocreate im SmartHome (FHEM) wurde das Device angelegt, jedoch geschieht das nun bei jedem Neustart des Vallox Containers immer wieder neu und die Devices haben eine unterschiedliche ClientID .
Kann man die ClientID in der Vallox Config fest vergeben?

VG Christian

**Comment by cheick66** [comment]
Und nochmal ich :-)
Ich habe eine Vallox 270 MV

Bei den Metriken wären da noch weitere möglich:
  - A_CYC_MODE
  - A_CYC_STATE
  - A_CYC_CELL_STATE
  - A_CYC_IN_BYPASS
  - A_CYC_MACHINE_MODEL
  - A_CYC_DAY
  - A_CYC_MONTH
  - A_CYC_YEAR
  - A_CYC_HOUR
  - A_CYC_MINUTE
  - A_CYC_MACHINE_TYPE
  - A_CYC_FILTER_CHANGED_DAY
  - A_CYC_FILTER_CHANGED_MONTH
  - A_CYC_FILTER_CHANGED_YEAR
  - A_CYC_REMAINING_TIME_FOR_FILTER
  - A_CYC_BOOST_TIMER
  - A_CYC_FIREPLACE_TIMER
  - A_CYC_EXTRA_TIME
  - A_CYC_EXTRA_TIMER
  - A_CYC_EXTRA_TIMER_ENABLED
  - A_CYC_EXTRA_ENABLED
  - A_CYC_EXTRA_SUPP_FAN

Zusätzlich werte ich diese dann in Kombination aus, bzw formatiere mir die Datumsanzeigen:
EXT_CYC_TIME { sprintf("%0.2i:%0.2i",ReadingsVal("$name","A_CYC_HOUR",""), ReadingsVal("$name","A_CYC_MINUTE","")) } ,
EXT_CYC_DATE { sprintf("20%i.%0.2i.%0.2i",ReadingsVal("$name","A_CYC_YEAR",""), ReadingsVal("$name","A_CYC_MONTH",""), ReadingsVal("$name","A_CYC_DAY","")) } ,
EXT_CYC_FILTER_CHANGED_DATE { sprintf("20%i.%0.2i.%0.2i",ReadingsVal("$name","A_CYC_FILTER_CHANGED_YEAR",""), ReadingsVal("$name","A_CYC_FILTER_CHANGED_MONTH",""), ReadingsVal("$name","A_CYC_FILTER_CHANGED_DAY","") ) },
EXT_CYC_STATE {
if     (ReadingsVal("$name","A_CYC_BOOST_TIMER","?") > 0 ) {sprintf("%s", "Boost")}
elsif (ReadingsVal("$name","A_CYC_FIREPLACE_TIMER","?") > 0 ) {sprintf("%s", "Fireplace")}
elsif (ReadingsVal("$name","A_CYC_EXTRA_TIMER","?") > 0 ) {sprintf("%s", "Extra")}
elsif (ReadingsVal("$name","A_CYC_STATE","?") == 0 ) {sprintf("%s", "Home")}
else  {sprintf("%s", "Away")}
}, 
EXT_CYC_CELL_STATE {
if     (ReadingsVal("$name","A_CYC_CELL_STATE","?") == 0 ) {sprintf("%s", "WRG")}
elsif (ReadingsVal("$name","A_CYC_CELL_STATE","?") == 1 ) {sprintf("%s", "KRG")}
elsif (ReadingsVal("$name","A_CYC_CELL_STATE","?") == 2 ) {sprintf("%s", "Bypass")}
elsif (ReadingsVal("$name","A_CYC_CELL_STATE","?") == 3 ) {sprintf("%s", "Defrost")}
else  {sprintf("%s", "?")}
}

**Comment by cheick66** [comment]
Leider habe ich mit den set Topics noch Probleme.
Wie kann ich raus bekommen, wie die für eine Vallox 270 MV sein müssen?

**Comment by mruettgers** [comment]
Vielleicht hilft Dir die Liste der möglichen Konstanten dabei:
https://github.com/danielbayerlein/vallox-api/blob/master/lib/constants.js

Oder diese Auflistung in einer anderen Bibliothek:
https://github.com/yozik04/vallox_websocket_api#available-metrics

**Comment by mruettgers** [comment]
Ich habe eine aktualisierte Version hochgeladen.
Damit lässt sich die MQTT Client-ID jetzt konfigurieren:
```
mqtt:
  broker:
    host: 10.4.32.103
  base_topic: ventilation/unit/1
  client_id: my-client-id
```
